inherit_from:
  - .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable

RSpec/LetSetup:
  Enabled: true

RSpec/SubjectStub:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

Rails/BelongsTo:
  Enabled: true

Rails/Validation:
  Enabled: true

Rails/ApplicationController:
  Enabled: false

Rails/FilePath:
  Enabled: false

################## STYLE #################################

Style/SafeNavigation:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/TernaryParentheses:
  Enabled: false

Style/Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/AccessModifierDeclarations:
  Enabled: false

Style/ExpandPathArguments:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: true

Style/MultilineTernaryOperator:
  Description: >-
                 Avoid multi-line ?: (the ternary operator);
                 use if/unless instead.
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#no-multiline-ternary'
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    'default': '()'
    '%i':      '()'
    '%w':      '()'

Naming/VariableNumber:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Naming/PredicateName:
  Enabled: true

Naming/BlockParameterName:
  Enabled: true
  MinNameLength: 3
  AllowNamesEndingInNumbers: false
  AllowedNames: ["id", "to"]

Naming/MemoizedInstanceVariableName:
  Enabled: false

Layout/EmptyLines:
  Description: "Don't use several empty lines in a row."
  Enabled: false

Layout/ExtraSpacing:
  Description: 'Do not use unnecessary spacing.'
  Enabled: false

Layout/EmptyLineAfterMagicComment:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

##########################################################
Metrics/AbcSize:
  Enabled: true
  Max: 20

Metrics/BlockNesting:
  Enabled: true
  Max: 4

Metrics/ClassLength:
  Enabled: true
  Max: 100

Metrics/ModuleLength:
  Enabled: true
  Max: 100

Lint/AmbiguousBlockAssociation:
  Enabled: false

Lint/SendWithMixinArgument:
  Enabled: true

Lint/Debugger:
  Enabled: true

