default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  host: <%= ENV.fetch("DB_HOST") %>
  username: <%= ENV.fetch("DB_USERNAME") %>
  password: <%= ENV.fetch("DB_PASSWORD") %>

development:
  <<: *default
  database: aeres_development

test:
  <<: *default
  database: aeres_test

production:
  <<: *default
  database: aeres_production
  username: aeres
  password: <%= ENV['AERES_DATABASE_PASSWORD'] %>
