name: Rubocop

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.0
        bundler-cache: true
    - name: Install dependencies
      run: bundle install
    - name: Rubocop
      run: bundle exec rubocop

